### ISSUE TITLE
Improve posts readability

### ISSUE THREAD

**Issue by Arkham** [sasa1977/erlangelist#4]
Hi Sasa, huge fan here! I've read your book and I'm an avid reader of your blog as well. A pet peeve I have with the current design is that the text is not very readable, so I wanted to hear your thoughts on it. My main issues are with the thickness of the font and the character count per line (https://baymard.com/blog/line-length-readability). I've also included a small preview of how it could look like.

## Current design

External Display (1920 x 858 pixels)

![screen shot 2017-04-11 at 15 40 30](https://cloud.githubusercontent.com/assets/62895/24914858/63b8d8cc-1ecd-11e7-8af6-49ce0e06d565.png)

Retina Display (2560 × 1360 pixels)

<img width="1280" alt="screen shot 2017-04-11 at 15 42 04" src="https://cloud.githubusercontent.com/assets/62895/24914930/a85865ce-1ecd-11e7-982d-50505bfb83d6.png">

## Possible Improvement

External Display (1920 x 858 pixels)

![screen shot 2017-04-11 at 15 45 33](https://cloud.githubusercontent.com/assets/62895/24915049/fc746806-1ecd-11e7-9904-d873ebe1015f.png)

Retina Display (2560 × 1360 pixels)

<img width="1280" alt="screen shot 2017-04-11 at 15 45 47" src="https://cloud.githubusercontent.com/assets/62895/24915056/0070fd34-1ece-11e7-8993-eda7274c63d0.png">

## Sample CSS

```css
body {
  font-family: Helvetica,Arial,sans-serif;
}

.container-fluid {
  max-width: 70em;
}
```

**Comment by sasa1977** [comment]
Hey, thanks for this! I'm terrible at UI, and the site design reflects that, so I appreciate your help :-)
Your screenshots look much better!

I'll try your suggestion on my machine (though not sure if I'll make it today), and if everything is fine, I'll deploy.

Alternatively, if you want to get proper credits and all, you can make a PR. I guess that [this](https://github.com/sasa1977/erlangelist/blob/master/site/web/static/css/site/post.css) would be the place to insert the new CSS rules. But if you don't care about all that, I'm totally fine with doing it myself :-)

**Comment by sasa1977** [comment]
Hey, I made the changes you suggested, and pushed the new version. I also decided to reduce code font to 13px (previously 14), to be able to write 80char lines. Would you please take a look and let me know if you're happy with it?

**Comment by Arkham** [comment]
Looks great now! 🎊
