### ISSUE TITLE
BlackJack reports incorrect winner

### ISSUE THREAD

**Issue by seanhandley** [sasa1977/erlangelist#6]
```
$ mix run -e Demo.run --no-halt
==> dialyxir
Compiling 5 files (.ex)
Generated dialyxir app
==> blackjack
Compiling 7 files (.ex)
Generated blackjack app
player_1: jack of clubs
player_1: 6 of clubs
player_1: thinking ...
player_1: hit
player_1: 3 of hearts
player_1: thinking ...
player_1: stand

player_2: 9 of diamonds
player_2: 7 of diamonds
player_2: thinking ...
player_2: stand

player_3: 8 of diamonds
player_3: king of hearts
player_3: thinking ...
player_3: stand

player_4: 3 of diamonds
player_4: king of spades
player_4: thinking ...
player_4: hit
player_4: 10 of diamonds
player_5: 9 of hearts
player_4: busted

player_5: 3 of spades
player_5: thinking ...
player_5: hit
player_5: 8 of hearts
player_5: thinking ...
player_5: stand

player_5: won
```

Player five scores 11, beaten by player 1's 19, player 2's 16, and player 3's 18.

**Comment by sasa1977** [comment]
Player 5 is in fact the winner. If you take a look more closely, immediately above `player_4` busted, you'll see `player_5: 9 of hearts`, meaning that the player 5 has in fact the score of 20.

You might wonder why the player 5 receives the notification about the first card before the player 4 received the notification that it was busted. I explained this at the end of the "Sending notifications" section:

![image](https://user-images.githubusercontent.com/202498/29997939-0d4bbd78-9020-11e7-8052-02772706ce26.png)

**Comment by seanhandley** [comment]
Aha! My bad, I completely missed that line. 

Thanks very much for the clarification @sasa1977 👍
